name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # updated Node.js version

    steps:
    - uses: actions/checkout@v4   # updated

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4   # updated
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: npm start
